export const data = [
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 2, 0, ["reference"]],
    },
    rankNum: 0,
    rowNum: 2,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "31 August",
        availabilityStartTime: 1693465200000,
        unplayableCause: null,
      },
      bookmarkPosition: -1,
      episodeBookmark: -1,
      episodeId: 80218003,
      episodeRuntime: 0,
      episodeTitle: "",
      evidenceData: {
        type: "NONE",
        key: "",
      },
      hasInfoDensityData: false,
      hasVideoMerch: true,
      hasAudioDescription: false,
      id: 80217863,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABQ3cD-TAmj6o4HamSRl_I4ZIxK-3ikU6PLRGNHr-oCrdO7ZqXEinro5arvsooFmspYkKjnwpd5wcp2EWittrLwXLwmV9XE7E4f96pTx8YdDJmzP3kAE5c1PGqX6Th9Uj7dafur2EHWDTJ4HOZbv8ZSNYp-ubC6M5YhwpQ9wZytaAPCzPUhP5hxcrqpa2xaxhCEOwjPPXZ3XwqUunAOJwspyPS0rB9Oq6OBhWqKrds8lYmzU9IHgWArP_3vqsV70dNW_UN-rEI2NeuDTbYOrLs7MP3uiSOLwuLfPen_QVt5XXtvUnFqQy4F-7UYbLSOO1naOrbDknxXTe10HkDt5JnwKGgqPYqOy8tsxkim2vCDYA-qaGZpc.jpg?r=6ab",
      imageKey:
        "sdp|72d8eff0-3c89-11ee-9872-12a13558ea1f|en,BADGE|recently.added|en",
      infoDensitySynopsis: "",
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: true,
      isPlayable: true,
      isStandalone: false,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "U/A 16+",
          maturityDescription:
            "Suitable for persons aged 16 and above and under parental guidance for people under age of 16",
          specificRatingReason: "self-harm, tobacco use",
          maturityLevel: 110,
          board: "India",
          boardId: 23821,
          ratingId: 23884,
          reasons: [
            {
              id: 23843,
              levelDescription: null,
              reasonDescription: "self-harm",
            },
            {
              id: 24141,
              levelDescription: null,
              reasonDescription: "tobacco use",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: "8 Episodes",
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2023,
      resumeParams: {
        SEASON_NUMBER: 1,
        EPISODE_NUMBER: 1,
      },
      requestId: "bb2b555e-5a7d-4cd3-bace-7e34c6eb5274-41817276",
      runtime: 0,
      infoDensityRuntime: 0,
      seasonCount: 1,
      summary: {
        unifiedEntityId: "Video:80217863",
        id: 80217863,
        type: "show",
        isOriginal: true,
      },
      title: "ONE PIECE",
      unifiedEntityId: "Video:80217863",
      userRating: {},
      userRatingRequestId: "bb2b555e-5a7d-4cd3-bace-7e34c6eb5274-41817276",
      videoMerchAspectRatio: "16x9",
      videoMerchComputeId: "browse|81703375|en-IN|_UPD_",
      videoMerchId: 81703375,
      videoMerchStartTime: 0,
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABQ3cD-TAmj6o4HamSRl_I4ZIxK-3ikU6PLRGNHr-oCrdO7ZqXEinro5arvsooFmspYkKjnwpd5wcp2EWittrLwXLwmV9XE7E4f96pTx8YdDJmzP3kAE5c1PGqX6Th9Uj7dafur2EHWDTJ4HOZbv8ZSNYp-ubC6M5YhwpQ9wZytaAPCzPUhP5hxcrqpa2xaxhCEOwjPPXZ3XwqUunAOJwspyPS0rB9Oq6OBhWqKrds8lYmzU9IHgWArP_3vqsV70dNW_UN-rEI2NeuDTbYOrLs7MP3uiSOLwuLfPen_QVt5XXtvUnFqQy4F-7UYbLSOO1naOrbDknxXTe10HkDt5JnwKGgqPYqOy8tsxkim2vCDYA-qaGZpc.jpg?r=6ab",
      isValid: true,
      jawSynopsis: "",
      availabilityEndDateNear: "",
      titleType: "video",
      liveEvent: {},
      inRemindMeList: false,
    },
    actionURL:
      "/watch/80217863?tctx=2%2C0%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A80217863%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 2, 2, ["reference"]],
    },
    rankNum: 2,
    rowNum: 2,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "14 July",
        availabilityStartTime: 1657782000000,
        unplayableCause: null,
      },
      bobSupplementalMessage: "Watch Season 3 now",
      currentSynopsis:
        "Po's popularity is gone after wicked weasels steal a powerful gauntlet. English knight Wandering Blade offers a chance to chase down the thieves.",
      dpContextualSynopsis: {
        text: "Legendary warrior Po teams up with an elite English knight on a global quest to rescue magical weapons, restore his reputation — and save the world!",
        evidenceKey: "web_synopsis|81227574_INFORMATIVE|en|_IFD_",
      },
      dpCurrentContextualSynopsis: {
        text: "Po's popularity is gone after wicked weasels steal a powerful gauntlet. English knight Wandering Blade offers a chance to chase down the thieves.",
        evidenceKey: "web_synopsis|81246478_INFORMATIVE|en",
      },
      dpSupplementalMessage: "#10 in TV Shows Today",
      dpSupplementalMessageIcon: "TOP_10",
      delivery: {
        has3D: false,
        hasHD: true,
        hasUltraHD: false,
        hasHDR: false,
        hasDolbyVision: false,
        hasDolbyAtmos: false,
        has51Audio: true,
        quality: "HD",
        hasAudioAssistive: true,
        hasTextClosedCaptions: true,
        hasAudioSpatial: false,
      },
      episodeBadges: [],
      episodeBookmark: -1,
      episodeId: 81246478,
      episodeRuntime: 1462,
      episodeDisplayRuntime: 1462,
      episodeTitle: "",
      evidenceData: {
        type: "NONE",
        key: "",
      },
      evidenceTags: {
        type: "TAGS",
        value: ["Exciting", "Kids", "Girl Power"],
        key: "UNKNOWN|81227574_TAGS|en-IN",
      },
      hasInfoDensityData: false,
      hasVideoMerch: true,
      hasAudioDescription: true,
      id: 81227574,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABZjKXf0ZjiNlVLaa2p6otiF4sevJAz5K5DmAVSJdR_8ypLQGOxmrwWmDMKruOZgnYnreS1-IfPmwzQwvnQoJEYcC66AHv-PX488MAQxE1ZlYrPy5liMCZbzlXwatMwR00z27axmYd81UbNmZwucyqMrI9uuaueo8KjwoWcbBVEU-Vs03oHok7_wZv2RyFodLEzJUWyoPq9f6sxNEjJQAHjv8vR-eofXONnDp9uS2xv7McU7DfQ5GGmHnwJQkDXsws1k-OYZT2t7fkWRrA77M0gRoWz0J1E1suJpEsly6nYgv7euEeWY8TfysYFSNPvb8bMh_TPCRN5XOyAXGCGTD4VPzRxlFZcTZJaxcu7z5bZsHrQ.jpg?r=4a3",
      imageHighRes:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABbPjWL8LGjYFnekNY851LUk3YEq5-O-Cs2z84Z4hBfUvXhGEomuvo9sBb1TJr1NLOyWUSTSHEfVW07oC6Pk0oNZvdL70yaYjUylrxaiXMNX4a3i33l_IcAExcl2iREFS7jPqFmLqlqDnVhGkhgD5-4jJFM1ACKxzg6WRTzKpNlAGLv-jL2vxvoIcAl5qVBD4nEUnV5k_CDEHmEMN9BP3KBr4bjfmn8LgTAsFmKo0gKAcrYAMr-ndYVFh7Vz8cJI8pnDR3AdexuIGbo_e0deEZYxXkov1PkGGQBcrpwV4Va_tkZP4FNMyuUKrF405stg_HH2I_3vagCJA4qzB-Rlv_FUA3_37rjVcwhiCJdYOvJ2r2P8.jpg?r=4a3",
      imageKey:
        "sdp|b4215270-30c4-11ee-9699-0a3b43006157|en,BADGE|newcontent:new.season|en",
      infoDensitySynopsis: "",
      interactiveBookmark: null,
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: true,
      isPlayable: false,
      isStandalone: false,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "U/A 7+",
          maturityDescription:
            "Suitable for children 7 and above and under parental guidance for persons under age of 7",
          specificRatingReason: "mild fear, mild language, mild violence",
          maturityLevel: 41,
          board: "India",
          boardId: 23821,
          ratingId: 23883,
          reasons: [
            {
              id: 23849,
              levelDescription: null,
              reasonDescription: "mild fear",
            },
            {
              id: 23866,
              levelDescription: null,
              reasonDescription: "mild language",
            },
            {
              id: 23869,
              levelDescription: null,
              reasonDescription: "mild violence",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: "3 Seasons",
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2023,
      resumeParams: {},
      requestId: "d4f200e3-922f-4860-acde-652393e629e0-62278344",
      runtime: 0,
      infoDensityRuntime: 0,
      seasonCount: 3,
      summary: {
        unifiedEntityId: "Video:81227574",
        id: 81227574,
        type: "show",
        isOriginal: true,
      },
      synopsis:
        "Legendary warrior Po teams up with an elite English knight on a global quest to rescue magical weapons, restore his reputation — and save the world!",
      title: "Kung Fu Panda: The Dragon Knight",
      unifiedEntityId: "Video:81227574",
      userRating: {
        type: "thumb",
        userRating: 0,
        matchScore: 94,
        tooNewForMatchScore: false,
        reactionUserRating: "THUMBS_UNRATED",
      },
      userRatingRequestId: "d4f200e3-922f-4860-acde-652393e629e0-62278344",
      videoMerchAspectRatio: "16x9",
      videoMerchComputeId: "browse|81646554|en-IN|_UPD_",
      videoMerchId: 81646554,
      videoMerchStartTime: 0,
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABZjKXf0ZjiNlVLaa2p6otiF4sevJAz5K5DmAVSJdR_8ypLQGOxmrwWmDMKruOZgnYnreS1-IfPmwzQwvnQoJEYcC66AHv-PX488MAQxE1ZlYrPy5liMCZbzlXwatMwR00z27axmYd81UbNmZwucyqMrI9uuaueo8KjwoWcbBVEU-Vs03oHok7_wZv2RyFodLEzJUWyoPq9f6sxNEjJQAHjv8vR-eofXONnDp9uS2xv7McU7DfQ5GGmHnwJQkDXsws1k-OYZT2t7fkWRrA77M0gRoWz0J1E1suJpEsly6nYgv7euEeWY8TfysYFSNPvb8bMh_TPCRN5XOyAXGCGTD4VPzRxlFZcTZJaxcu7z5bZsHrQ.jpg?r=4a3",
      isValid: true,
      moodTags: [
        {
          id: 100041,
          name: "Exciting",
        },
      ],
      genres: [
        {
          id: 27346,
          name: "Kids' TV",
        },
        {
          id: 10375,
          name: "TV Comedies",
        },
        {
          id: 11177,
          name: "TV Cartoons",
        },
      ],
      cast: [
        {
          id: 20007783,
          name: "Jack Black",
        },
        {
          id: 30205963,
          name: "Rita Ora",
        },
        {
          id: 42909,
          name: "James Hong",
        },
        {
          id: 30095822,
          name: "Chris Geere",
        },
        {
          id: 20027112,
          name: "Amy Hill",
        },
        {
          id: 30086805,
          name: "Nolan North",
        },
        {
          id: 60632602,
          name: "Della Saba",
        },
      ],
      jawSynopsis:
        "Legendary warrior Po teams up with an elite English knight on a global quest to rescue magical weapons, restore his reputation — and save the world!",
      creators: [],
      directors: [],
      writers: [],
      broadcaster: {
        broadcasterName: null,
      },
      copyright: null,
      availabilityEndDateNear: "",
      jawTrackIds: {
        trackId_jaw: 15036064,
        trackId_jawEpisode: 15036065,
        trackId_jawTrailer: "15036066",
        trackId: 15035895,
        videoId: 81227574,
      },
      titleType: "video",
      liveEvent: {},
      logo: {
        videoId: 81227574,
        url: "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/tx1O544a9T7n8Z_G12qaboulQQE/AAAABe4VHKlIF5u1HPyYsHgMB0t44Zx8B6XxaRzKnZAO2fKZ-bcwZ03nALhdtb-Plo1nHhtNCNi6ewe5vMpIkZ01JG8Nq0Hg1tixNRzk3bXlP1yiPRuoAcn8cjzM2c1IZUg32cZnFbDz-uXjY8jJJy0oASBTBXR881DsGLwOxjyMBzjwYewsRorF.webp?r=789",
        type: "LOGO_BRANDED_HORIZONTAL",
        width: 625,
        height: 250,
        extension: "webp",
        size: "_LOGO_BRANDED_HORIZONTAL",
        imageKey:
          "LOGO_BRANDED_HORIZONTAL|829513a0-229a-11ee-ac1c-12b65e122841:6bc1ad90-7e71-11e9-a86a-0ef4f0f37a06|en",
      },
      storyArt: {
        videoId: 81227574,
        url: "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABWZEVtbyco0VjgwGWCSBkVNc5IkBu0xdPAqErPtlKPt-Bo77b597JYTMano18sKfiUzNduXFz_DWZMxpFJxYrOKwi5nrzQrsGzoj.webp?r=e64",
        width: 848,
        height: 477,
        extension: "webp",
        size: 480,
        focalPoint: '{"x":0.5231,"y":0.5651}',
        imageKey: "StoryArt|ac48a7b0-30c4-11ee-9a5b-0ed820da1b0d|en",
      },
      inRemindMeList: false,
    },
    actionURL:
      "/watch/81227574?tctx=2%2C2%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A81227574%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 3, 2, ["reference"]],
    },
    rankNum: 2,
    rowNum: 3,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "20 December",
        availabilityStartTime: 1576828800000,
        unplayableCause: null,
      },
      episodeBadges: [],
      episodeBookmark: -1,
      episodeId: 80189599,
      episodeRuntime: 0,
      episodeTitle: "",
      evidenceData: {
        type: "NONE",
        key: "",
      },
      hasInfoDensityData: false,
      hasVideoMerch: true,
      hasAudioDescription: false,
      id: 80189685,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWBgKNsLo6EECdsaI632R9PI7zpwnu_I4J6Q_bYyPzd3DBsPLNnbIJqaf-xy46ekLBGJSnhYIcOvKk6HjkLNc_EXNURHIDuo08Z1i-3-s8ory_YRrRWT1McQrxcKL5p-g3fO.jpg?r=bb3",
      imageKey: "sdp|445d2070-1ff0-11ee-99e6-0e7de33fe40b|en",
      infoDensitySynopsis: "",
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: true,
      isPlayable: false,
      isStandalone: false,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "A",
          maturityDescription: "Content restricted to adults",
          specificRatingReason:
            "gore, nudity, self-harm, sex, suicide, tobacco use, violence",
          maturityLevel: 1000,
          board: "India",
          boardId: 23821,
          ratingId: 23885,
          reasons: [
            {
              id: 23858,
              levelDescription: null,
              reasonDescription: "gore",
            },
            {
              id: 23870,
              levelDescription: null,
              reasonDescription: "nudity",
            },
            {
              id: 23843,
              levelDescription: null,
              reasonDescription: "self-harm",
            },
            {
              id: 23844,
              levelDescription: null,
              reasonDescription: "sex",
            },
            {
              id: 23867,
              levelDescription: null,
              reasonDescription: "suicide",
            },
            {
              id: 24141,
              levelDescription: null,
              reasonDescription: "tobacco use",
            },
            {
              id: 23845,
              levelDescription: null,
              reasonDescription: "violence",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: "3 Seasons",
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2023,
      resumeParams: {},
      requestId: "9f2967a0-aff0-4ad1-9689-58660455d02d-563095445",
      runtime: 0,
      infoDensityRuntime: 0,
      seasonCount: 3,
      summary: {
        unifiedEntityId: "Video:80189685",
        id: 80189685,
        type: "show",
        isOriginal: true,
      },
      title: "The Witcher",
      unifiedEntityId: "Video:80189685",
      userRating: {},
      userRatingRequestId: "9f2967a0-aff0-4ad1-9689-58660455d02d-563095445",
      videoMerchAspectRatio: "16x9",
      videoMerchComputeId: "browse|81678923|en-IN|_UPD_",
      videoMerchId: 81678923,
      videoMerchStartTime: 0,
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWBgKNsLo6EECdsaI632R9PI7zpwnu_I4J6Q_bYyPzd3DBsPLNnbIJqaf-xy46ekLBGJSnhYIcOvKk6HjkLNc_EXNURHIDuo08Z1i-3-s8ory_YRrRWT1McQrxcKL5p-g3fO.jpg?r=bb3",
      isValid: true,
      jawSynopsis: "",
      availabilityEndDateNear: "",
      titleType: "video",
      liveEvent: {},
      inRemindMeList: false,
    },
    actionURL:
      "/watch/80189685?tctx=3%2C2%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A80189685%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 2, 4, ["reference"]],
    },
    rankNum: 4,
    rowNum: 2,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "20 December",
        availabilityStartTime: 1513756800000,
        unplayableCause: null,
      },
      episodeBadges: [],
      episodeBookmark: -1,
      episodeId: 80205342,
      episodeRuntime: 0,
      episodeTitle: "",
      evidenceData: {
        type: "NONE",
        key: "",
      },
      hasInfoDensityData: false,
      hasVideoMerch: true,
      hasAudioDescription: false,
      id: 80192098,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABbzBukwj-wl3qePSdFwS-Nwy6BGO7tIdqQ0oFSWYKqpdhrmIcLeD0CYnBd81oVLyS7eu5sROjfsOCmJmxso3w8xcqDcCdNitNN6nUpm2nLIKIbB7PUAsftFJnfhUpQk0tEi0.jpg?r=8a4",
      imageKey: "sdp|f881eb71-52f2-11ec-ae13-0e18a7e7ced3|en",
      infoDensitySynopsis: "",
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: true,
      isPlayable: false,
      isStandalone: false,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "A",
          maturityDescription: "Content restricted to adults",
          specificRatingReason:
            "language, nudity, sex, sexual violence, substances, tobacco use, violence",
          maturityLevel: 1000,
          board: "India",
          boardId: 23821,
          ratingId: 23885,
          reasons: [
            {
              id: 23854,
              levelDescription: null,
              reasonDescription: "language",
            },
            {
              id: 23870,
              levelDescription: null,
              reasonDescription: "nudity",
            },
            {
              id: 23844,
              levelDescription: null,
              reasonDescription: "sex",
            },
            {
              id: 23860,
              levelDescription: null,
              reasonDescription: "sexual violence",
            },
            {
              id: 23852,
              levelDescription: null,
              reasonDescription: "substances",
            },
            {
              id: 24141,
              levelDescription: null,
              reasonDescription: "tobacco use",
            },
            {
              id: 23845,
              levelDescription: null,
              reasonDescription: "violence",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: "5 Parts",
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2021,
      resumeParams: {},
      requestId: "9f2967a0-aff0-4ad1-9689-58660455d02d-563095445",
      runtime: 0,
      infoDensityRuntime: 0,
      seasonCount: 5,
      summary: {
        unifiedEntityId: "Video:80192098",
        id: 80192098,
        type: "show",
        isOriginal: true,
      },
      title: "Money Heist",
      unifiedEntityId: "Video:80192098",
      userRating: {},
      userRatingRequestId: "9f2967a0-aff0-4ad1-9689-58660455d02d-563095445",
      videoMerchAspectRatio: "16x9",
      videoMerchComputeId: "browse|81519435|en-IN|_UPD_",
      videoMerchId: 81519435,
      videoMerchStartTime: 0,
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABbzBukwj-wl3qePSdFwS-Nwy6BGO7tIdqQ0oFSWYKqpdhrmIcLeD0CYnBd81oVLyS7eu5sROjfsOCmJmxso3w8xcqDcCdNitNN6nUpm2nLIKIbB7PUAsftFJnfhUpQk0tEi0.jpg?r=8a4",
      isValid: true,
      jawSynopsis: "",
      availabilityEndDateNear: "",
      titleType: "video",
      liveEvent: {},
      inRemindMeList: false,
    },
    actionURL:
      "/watch/80192098?tctx=2%2C4%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A80192098%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 6, 4, ["reference"]],
    },
    rankNum: 4,
    rowNum: 6,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "10 October",
        availabilityStartTime: 1633881600000,
        unplayableCause: null,
      },
      episodeBadges: [],
      episodeBookmark: -1,
      episodeId: 81091395,
      episodeRuntime: 0,
      episodeTitle: "",
      evidenceData: {
        type: "NONE",
        key: "",
      },
      hasInfoDensityData: false,
      hasVideoMerch: true,
      hasAudioDescription: false,
      id: 81091393,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWE6SZxovoWEqL9o2ww1MENZQ4YrcD9A03i9YR9IBNNQzcHfwX6FHqTtigxXtfqTkJ6XDONhPjrFxgbPoxSQRWXpJP0sY-i7Gv4.webp?r=27e",
      imageKey: "sdp|b850a9f0-d51f-11ed-ada2-1206d2af9e11|en",
      infoDensitySynopsis: "",
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: false,
      isPlayable: false,
      isStandalone: false,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "U/A 16+",
          maturityDescription:
            "Suitable for persons aged 16 and above and under parental guidance for people under age of 16",
          specificRatingReason: "gore, self-harm, tobacco use, violence",
          maturityLevel: 110,
          board: "India",
          boardId: 23821,
          ratingId: 23884,
          reasons: [
            {
              id: 23858,
              levelDescription: null,
              reasonDescription: "gore",
            },
            {
              id: 23843,
              levelDescription: null,
              reasonDescription: "self-harm",
            },
            {
              id: 24141,
              levelDescription: null,
              reasonDescription: "tobacco use",
            },
            {
              id: 23845,
              levelDescription: null,
              reasonDescription: "violence",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: "4 Seasons",
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2023,
      resumeParams: {},
      requestId: "d4f200e3-922f-4860-acde-652393e629e0-62013933",
      runtime: 0,
      infoDensityRuntime: 0,
      seasonCount: 4,
      summary: {
        unifiedEntityId: "Video:81091393",
        id: 81091393,
        type: "show",
        isOriginal: false,
      },
      title: "Demon Slayer: Kimetsu no Yaiba",
      unifiedEntityId: "Video:81091393",
      userRating: {
        type: "thumb",
        userRating: 0,
        matchScore: 97,
        tooNewForMatchScore: false,
        reactionUserRating: "THUMBS_UNRATED",
      },
      userRatingRequestId: "d4f200e3-922f-4860-acde-652393e629e0-62013933",
      videoMerchAspectRatio: "16x9",
      videoMerchComputeId: "browse|81102675|en-IN|_UPD_",
      videoMerchId: 81102675,
      videoMerchStartTime: 0,
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWE6SZxovoWEqL9o2ww1MENZQ4YrcD9A03i9YR9IBNNQzcHfwX6FHqTtigxXtfqTkJ6XDONhPjrFxgbPoxSQRWXpJP0sY-i7Gv4.webp?r=27e",
      isValid: true,
      jawSynopsis: "",
      availabilityEndDateNear: "",
      mostLiked: "Most Liked",
      titleType: "video",
      liveEvent: {},
      inRemindMeList: false,
    },
    actionURL:
      "/watch/81091393?tctx=6%2C4%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A81091393%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 10, 1, ["reference"]],
    },
    rankNum: 1,
    rowNum: 10,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "7 September",
        availabilityStartTime: 1694111400000,
        unplayableCause: null,
      },
      bookmarkPosition: -1,
      displayRuntime: 7464,
      episodeBookmark: -1,
      episodeRuntime: 0,
      episodeDisplayRuntime: 7464,
      episodeTitle: "Sonic the Hedgehog 2",
      evidenceData: {
        type: "NONE",
        key: "",
      },
      hasInfoDensityData: false,
      hasVideoMerch: false,
      hasAudioDescription: false,
      id: 81511780,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABfRDzPMkAfU03IEAgKZ2gTbS3saC-McsUx3AkS5JtsOGBYwvvJOBo4G5hjJyU53_pWNxWBQBLdNtx0D-KgQAhtbQD0bgwJFliGoXdKDDnx11B0sfYuzVGJL0mH13TwsjLQSCpmqdZ7rjUHDlufrxLUH4qN9R1dw5FUM.webp?r=ebb",
      imageKey: "sdp|85f2de00-a1cc-11ed-84ab-0eeec5ad4a87|en",
      infoDensitySynopsis: "",
      interactiveBookmark: null,
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: false,
      isPlayable: true,
      isStandalone: true,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "U/A 7+",
          maturityDescription:
            "Suitable for children 7 and above and under parental guidance for persons under age of 7",
          specificRatingReason: "mild fear, mild language, mild violence",
          maturityLevel: 41,
          board: "India",
          boardId: 23821,
          ratingId: 23883,
          reasons: [
            {
              id: 23849,
              levelDescription: null,
              reasonDescription: "mild fear",
            },
            {
              id: 23866,
              levelDescription: null,
              reasonDescription: "mild language",
            },
            {
              id: 23869,
              levelDescription: null,
              reasonDescription: "mild violence",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: null,
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2022,
      resumeParams: {
        TITLE: "Sonic the Hedgehog 2",
      },
      requestId: "d4f200e3-922f-4860-acde-652393e629e0-62013933",
      runtime: 7464,
      infoDensityRuntime: 7464,
      summary: {
        unifiedEntityId: "Video:81511780",
        id: 81511780,
        type: "movie",
        isOriginal: false,
      },
      title: "Sonic the Hedgehog 2",
      unifiedEntityId: "Video:81511780",
      userRating: {
        type: "thumb",
        userRating: 0,
        tooNewForMatchScore: true,
        reactionUserRating: "THUMBS_UNRATED",
      },
      userRatingRequestId: "d4f200e3-922f-4860-acde-652393e629e0-62013933",
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABfRDzPMkAfU03IEAgKZ2gTbS3saC-McsUx3AkS5JtsOGBYwvvJOBo4G5hjJyU53_pWNxWBQBLdNtx0D-KgQAhtbQD0bgwJFliGoXdKDDnx11B0sfYuzVGJL0mH13TwsjLQSCpmqdZ7rjUHDlufrxLUH4qN9R1dw5FUM.webp?r=ebb",
      isValid: true,
      jawSynopsis: "",
      availabilityEndDateNear: "",
      titleType: "video",
      liveEvent: {},
      inRemindMeList: false,
    },
    actionURL:
      "/watch/81511780?tctx=10%2C1%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A81511780%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 13, 1, ["reference"]],
    },
    rankNum: 1,
    rowNum: 13,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "13 April",
        availabilityStartTime: 1523602800000,
        unplayableCause: null,
      },
      bobSupplementalMessage: "",
      currentSynopsis:
        "On the way to a space colony, a crisis sends the Robinsons hurtling toward an unfamiliar planet, where they struggle to survive a harrowing night.",
      dpContextualSynopsis: {
        text: "After crash-landing on an alien planet, the Robinson family fights against all odds to survive and escape. But they're surrounded by hidden dangers.",
        evidenceKey: "web_synopsis|80104198_INFORMATIVE|en|_IFD_",
      },
      dpCurrentContextualSynopsis: {
        text: "On the way to a space colony, a crisis sends the Robinsons hurtling toward an unfamiliar planet, where they struggle to survive a harrowing night.",
        evidenceKey: "web_synopsis|80117488_INFORMATIVE|en",
      },
      dpSupplementalMessageIcon: "REGULAR",
      bookmarkPosition: -1,
      delivery: {
        has3D: false,
        hasHD: true,
        hasUltraHD: false,
        hasHDR: false,
        hasDolbyVision: false,
        hasDolbyAtmos: false,
        has51Audio: true,
        quality: "HD",
        hasAudioAssistive: true,
        hasTextClosedCaptions: true,
        hasAudioSpatial: false,
      },
      episodeBookmark: -1,
      episodeId: 80117488,
      episodeRuntime: 3831,
      episodeDisplayRuntime: 3831,
      episodeTitle: "Impact",
      evidenceData: {
        type: "TAGS",
        value: ["Slick", "Suspenseful", "Adventure"],
        key: "UNKNOWN|80104198_TAGS|en-IN",
      },
      evidenceTags: {
        type: "TAGS",
        value: ["Slick", "Suspenseful", "Adventure"],
        key: "UNKNOWN|80104198_TAGS|en-IN",
      },
      hasInfoDensityData: false,
      hasVideoMerch: true,
      hasAudioDescription: true,
      id: 80104198,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABZjE2zN-_91rykScSv9nFDQ5usjgsMZASGAxEpiZfFUYqKtPc9adMwqHFL-3uR-6Yxgef5QMX7M9dyo-ZBHgBrqTBRD2ZYgGizyFUwm-xbFQmPDslw6LF6QhZV_WoQoKjDrH.jpg?r=0b3",
      imageHighRes:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABXZpL36z4r0roSNKu85EPUFeucVzH-wi3jl9mQZQkrX-0PDQcdfR2oZSeXO585rd6jqdkYPS0FJtdcq8O0gr-CErSmJCqtPv-pZnfTjWgW5aWRTD9LbI_O_pa0VIoDOEQ3RLfg.jpg?r=0b3",
      imageKey: "sdp|c88b90c1-32b2-11ec-87da-0e06cc31e135|en",
      infoDensitySynopsis: "",
      interactiveBookmark: null,
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: true,
      isPlayable: true,
      isStandalone: false,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "U/A 7+",
          maturityDescription:
            "Suitable for children 7 and above and under parental guidance for persons under age of 7",
          specificRatingReason: "mild violence",
          maturityLevel: 41,
          board: "India",
          boardId: 23821,
          ratingId: 23883,
          reasons: [
            {
              id: 23869,
              levelDescription: null,
              reasonDescription: "mild violence",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: "3 Seasons",
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2021,
      resumeParams: {
        SEASON_NUMBER: 1,
        EPISODE_NUMBER: 1,
        TITLE: "Impact",
      },
      requestId: "d4f200e3-922f-4860-acde-652393e629e0-63096934",
      runtime: 0,
      infoDensityRuntime: 0,
      seasonCount: 3,
      summary: {
        unifiedEntityId: "Video:80104198",
        id: 80104198,
        type: "show",
        isOriginal: true,
      },
      synopsis:
        "After crash-landing on an alien planet, the Robinson family fights against all odds to survive and escape. But they're surrounded by hidden dangers.",
      title: "Lost in Space",
      unifiedEntityId: "Video:80104198",
      userRating: {
        type: "thumb",
        userRating: 0,
        matchScore: 96,
        tooNewForMatchScore: false,
        reactionUserRating: "THUMBS_UNRATED",
      },
      userRatingRequestId: "d4f200e3-922f-4860-acde-652393e629e0-63096934",
      videoMerchAspectRatio: "16x9",
      videoMerchComputeId: "browse|81515803|en-IN|_UPD_",
      videoMerchId: 81515803,
      videoMerchStartTime: 0,
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABZjE2zN-_91rykScSv9nFDQ5usjgsMZASGAxEpiZfFUYqKtPc9adMwqHFL-3uR-6Yxgef5QMX7M9dyo-ZBHgBrqTBRD2ZYgGizyFUwm-xbFQmPDslw6LF6QhZV_WoQoKjDrH.jpg?r=0b3",
      isValid: true,
      moodTags: [
        {
          id: 100055,
          name: "Suspenseful",
        },
      ],
      genres: [
        {
          id: 11714,
          name: "TV Dramas",
        },
        {
          id: 2072262,
          name: "Family Watch Together TV",
        },
        {
          id: 10673,
          name: "TV Action & Adventure",
        },
        {
          id: 72404,
          name: "US TV Shows",
        },
      ],
      cast: [
        {
          id: 182534,
          name: "Molly Parker",
        },
        {
          id: 20006835,
          name: "Toby Stephens",
        },
        {
          id: 40094665,
          name: "Maxwell Jenkins",
        },
        {
          id: 40005496,
          name: "Taylor Russell",
        },
        {
          id: 40079604,
          name: "Mina Sundwall",
        },
        {
          id: 152698,
          name: "Parker Posey",
        },
        {
          id: 30061115,
          name: "Ignacio Serricchio",
        },
      ],
      jawSynopsis:
        "After crash-landing on an alien planet, the Robinson family fights against all odds to survive and escape. But they're surrounded by hidden dangers.",
      creators: [],
      directors: [],
      writers: [],
      broadcaster: {
        broadcasterName: null,
        broadcastDate: "2018. 4. 13.",
      },
      copyright: null,
      availabilityEndDateNear: "",
      jawTrackIds: {
        trackId_jaw: 14292320,
        trackId_jawEpisode: 14170044,
        trackId_jawTrailer: "14170058",
        trackId: 14170035,
        videoId: 80104198,
      },
      titleType: "video",
      liveEvent: {},
      logo: {
        videoId: 80104198,
        url: "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/tx1O544a9T7n8Z_G12qaboulQQE/AAAABYVLa3GUFfXZR_MKb6TprSOcZhszpbCBk5V8UIUo3hBldtEjxC81Et5cSGJrtaSQf29XNHq3jRUiHiMO-8jSO7kCkDH7R3KyxheYDzjaLsgyPaveAhbCtoRHDVR7KcvsGLKhLZKjqtHEe9kV8TSbXUDaRK5ztfD8WlOoaBrfzzirMSZySa58.webp?r=112",
        type: "LOGO_BRANDED_HORIZONTAL",
        width: 625,
        height: 250,
        extension: "webp",
        size: "_LOGO_BRANDED_HORIZONTAL",
        imageKey:
          "LOGO_BRANDED_HORIZONTAL|f0084140-593e-11ec-8c21-1257bcfa2c09:6bc1ad90-7e71-11e9-a86a-0ef4f0f37a06|en",
      },
      storyArt: {
        videoId: 80104198,
        url: "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABbfMh-uiyBrgROr5656RD2DtUjJsRhAm4-3EBnOgEbTUnI6rwfPs_60HR6S6OJYJ2azCiGQ35hRfvu-oB6pSE28tRNlzCYZxf_Aa.webp?r=d96",
        width: 848,
        height: 477,
        extension: "webp",
        size: 480,
        focalPoint: '{"x":0.5154,"y":0.4783}',
        imageKey: "StoryArt|b08891f0-329c-11ec-a4af-0eb5d56dab9d|en",
      },
      inRemindMeList: false,
    },
    actionURL:
      "/watch/80104198?tctx=13%2C1%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A80104198%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 13, 5, ["reference"]],
    },
    rankNum: 5,
    rowNum: 13,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "10 December",
        availabilityStartTime: 1607587200000,
        unplayableCause: null,
      },
      bookmarkPosition: -1,
      episodeBookmark: -1,
      episodeId: 81035908,
      episodeRuntime: 0,
      episodeTitle: "",
      evidenceData: {
        type: "NONE",
        key: "",
      },
      hasInfoDensityData: false,
      hasVideoMerch: true,
      hasAudioDescription: false,
      id: 80200575,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABQiAZh-kUsfhvTz-LUZFyZ9bWEP7LAE7VN7KtRRH3ImZa0ocYqzJzPRgjpGRQTyz1-_sOUTjOWRDskhLjhCzwGieYfAABZZuTjonnoEVcHCPag3on-jB-cUPNnCxDUPQK8D2.jpg?r=400",
      imageKey: "sdp|54ed6ba0-7778-11ed-83a4-12bea06e8f81|en",
      infoDensitySynopsis: "",
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: true,
      isPlayable: true,
      isStandalone: false,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "A",
          maturityDescription: "Content restricted to adults",
          specificRatingReason:
            "sex, sexual violence, suicide, tobacco use, violence",
          maturityLevel: 1000,
          board: "India",
          boardId: 23821,
          ratingId: 23885,
          reasons: [
            {
              id: 23844,
              levelDescription: null,
              reasonDescription: "sex",
            },
            {
              id: 23860,
              levelDescription: null,
              reasonDescription: "sexual violence",
            },
            {
              id: 23867,
              levelDescription: null,
              reasonDescription: "suicide",
            },
            {
              id: 24141,
              levelDescription: null,
              reasonDescription: "tobacco use",
            },
            {
              id: 23845,
              levelDescription: null,
              reasonDescription: "violence",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: "2 Seasons",
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2022,
      resumeParams: {
        SEASON_NUMBER: 1,
        EPISODE_NUMBER: 1,
      },
      requestId: "d4f200e3-922f-4860-acde-652393e629e0-62013933",
      runtime: 0,
      infoDensityRuntime: 0,
      seasonCount: 2,
      summary: {
        unifiedEntityId: "Video:80200575",
        id: 80200575,
        type: "show",
        isOriginal: true,
      },
      title: "Alice in Borderland",
      unifiedEntityId: "Video:80200575",
      userRating: {},
      userRatingRequestId: "d4f200e3-922f-4860-acde-652393e629e0-62013933",
      videoMerchAspectRatio: "16x9",
      videoMerchComputeId: "browse|81644962|en-IN|_UPD_",
      videoMerchId: 81644962,
      videoMerchStartTime: 0,
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABQiAZh-kUsfhvTz-LUZFyZ9bWEP7LAE7VN7KtRRH3ImZa0ocYqzJzPRgjpGRQTyz1-_sOUTjOWRDskhLjhCzwGieYfAABZZuTjonnoEVcHCPag3on-jB-cUPNnCxDUPQK8D2.jpg?r=400",
      isValid: true,
      jawSynopsis: "",
      availabilityEndDateNear: "",
      titleType: "video",
      liveEvent: {},
      inRemindMeList: false,
    },
    actionURL:
      "/watch/80200575?tctx=13%2C5%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A80200575%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
  {
    type: "Default",
    className: "ltr-0",
    isBobOpen: false,
    isDimmed: false,
    isDisliked: false,
    isJAWOpen: false,
    isInvalid: false,
    itemTabbable: true,
    model: {
      $type: "ref",
      value: ["loco", 15, 2, ["reference"]],
    },
    rankNum: 2,
    rowNum: 15,
    showProgress: false,
    videoModel: {
      availability: {
        isPlayable: true,
        availabilityDate: "5 January",
        availabilityStartTime: 1452018600000,
        unplayableCause: null,
      },
      episodeBadges: [],
      episodeBookmark: -1,
      episodeId: 80021956,
      episodeRuntime: 0,
      episodeTitle: "",
      evidenceData: {
        type: "NONE",
        key: "",
      },
      hasInfoDensityData: false,
      hasVideoMerch: true,
      hasAudioDescription: false,
      id: 80021955,
      image:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWLCqe9_JhVUPEIYPW485WQD47kCaXwYY8cT3w4uXYdaYG3LrIk9puaUdfnZ4zAcr3IAzD0V_Odgn72VfOxhqMPGQKHQJSuEXfw.webp?r=696",
      imageKey: "sdp|1c1a9b00-a621-11ec-80ba-0e38d92cea73|en",
      infoDensitySynopsis: "",
      isBranching: false,
      isInteractive: false,
      isNSRE: false,
      isOriginal: false,
      isPlayable: false,
      isStandalone: false,
      interestingMoment: {},
      maturity: {
        rating: {
          value: "A",
          maturityDescription: "Content restricted to adults",
          specificRatingReason: "substances, suicide, tobacco use",
          maturityLevel: 1000,
          board: "India",
          boardId: 23821,
          ratingId: 23885,
          reasons: [
            {
              id: 23852,
              levelDescription: null,
              reasonDescription: "substances",
            },
            {
              id: 23867,
              levelDescription: null,
              reasonDescription: "suicide",
            },
            {
              id: 24141,
              levelDescription: null,
              reasonDescription: "tobacco use",
            },
          ],
        },
      },
      maturityMisMatchEdgy: false,
      maturityMisMatchNonEdgy: false,
      numSeasonsLabel: "6 Seasons",
      queue: {
        available: true,
        inQueue: false,
      },
      releaseYear: 2022,
      resumeParams: {},
      requestId: "d4f200e3-922f-4860-acde-652393e629e0-62013933",
      runtime: 0,
      infoDensityRuntime: 0,
      seasonCount: 6,
      summary: {
        unifiedEntityId: "Video:80021955",
        id: 80021955,
        type: "show",
        isOriginal: false,
      },
      title: "Better Call Saul",
      unifiedEntityId: "Video:80021955",
      userRating: {},
      userRatingRequestId: "d4f200e3-922f-4860-acde-652393e629e0-62013933",
      videoMerchAspectRatio: "16x9",
      videoMerchComputeId: "browse|81095035|en-IN|_UPD_",
      videoMerchId: 81095035,
      videoMerchStartTime: 0,
      watchState: "unwatched",
      wideImage:
        "https://occ-0-1492-3663.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWLCqe9_JhVUPEIYPW485WQD47kCaXwYY8cT3w4uXYdaYG3LrIk9puaUdfnZ4zAcr3IAzD0V_Odgn72VfOxhqMPGQKHQJSuEXfw.webp?r=696",
      isValid: true,
      jawSynopsis: "",
      availabilityEndDateNear: "",
      titleType: "video",
      liveEvent: {},
      inRemindMeList: false,
    },
    actionURL:
      "/watch/80021955?tctx=15%2C2%2C%2C%2C%2C%2C%2C%2C%2CVideo%3A80021955%2C",
    titleCardInfoDensityLogData: {},
    isLive: false,
    postLive: false,
  },
] as const;
